### ISSUE TITLE
GBF not logging turns

### ISSUE THREAD

**Issue by Azryth** [Azryth/gbf-extension#17]
From a user: "Hi Azryth, I recently found GBF logger and I really like the idea! However, it didn't work for me. I followed your instructions and it seems that functions other than Raid Ranking do not work. Is it because of the recent updates or I need to set something?"

**Comment by Azryth** [comment]
Hi anonymous user,

You probably did everything right, however there is an issue with chrome devtools right now (see [link](https://bugs.chromium.org/p/chromium/issues/detail?id=770130&q=form%20data&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified.)) If you still really want to use it, it seems to be fine on [Chrome Canary](https://www.google.com/chrome/browser/canary.html).

**Comment by trim21** [comment]
There is another bug on stable version of chrome.Extension doen't show battle log and characters damage
![image](https://user-images.githubusercontent.com/13553903/38174116-163e1c6a-35fb-11e8-8245-645d219ff6f9.png)

It's ok on Chrome Canary.

**Comment by Azryth** [comment]
The latest version of Chrome (v.66) no longer has this issue
